// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBe_ambczO5GiRY1ToHKl8ReFSAxMItKN0',
    appId: '1:200480492761:web:c30a66ffeb5f164d5ac2c8',
    messagingSenderId: '200480492761',
    projectId: 'pontocerto-83e68',
    authDomain: 'pontocerto-83e68.firebaseapp.com',
    storageBucket: 'pontocerto-83e68.firebasestorage.app',
    measurementId: 'G-NHMZWF4ZFC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA76h4ZpEGx3BMEDNjdc_eyw4vqFNou660',
    appId: '1:200480492761:android:faf323844ab67ad05ac2c8',
    messagingSenderId: '200480492761',
    projectId: 'pontocerto-83e68',
    storageBucket: 'pontocerto-83e68.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1wO6l0t9NLOMV9RQ2VMn8ZPuBx0nHzQ8',
    appId: '1:200480492761:ios:b75b82dcd3c07f575ac2c8',
    messagingSenderId: '200480492761',
    projectId: 'pontocerto-83e68',
    storageBucket: 'pontocerto-83e68.firebasestorage.app',
    iosBundleId: 'com.example.pontoDigitalApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1wO6l0t9NLOMV9RQ2VMn8ZPuBx0nHzQ8',
    appId: '1:200480492761:ios:b75b82dcd3c07f575ac2c8',
    messagingSenderId: '200480492761',
    projectId: 'pontocerto-83e68',
    storageBucket: 'pontocerto-83e68.firebasestorage.app',
    iosBundleId: 'com.example.pontoDigitalApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBe_ambczO5GiRY1ToHKl8ReFSAxMItKN0',
    appId: '1:200480492761:web:45ceec945599164c5ac2c8',
    messagingSenderId: '200480492761',
    projectId: 'pontocerto-83e68',
    authDomain: 'pontocerto-83e68.firebaseapp.com',
    storageBucket: 'pontocerto-83e68.firebasestorage.app',
    measurementId: 'G-EGQ63EDN86',
  );
}
