import 'package:flutter/material.dart';
import 'package:intl/date_symbol_data_local.dart';
// import 'package:firebase_core/firebase_core.dart';

// import 'services/push_service.dart';
// NOTE: you must provide firebase_options.dart generated by FlutterFire CLI
// import 'firebase_options.dart';
import 'theme.dart';
import 'views/auth/login_screen.dart';
import 'services/theme_service.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  
  // Inicializar dados de localização para pt_BR
  await initializeDateFormatting('pt_BR', null);
  // Inicializar serviço de tema (lê preferência salva)
  await ThemeService.init();
  
  // TODO: Configurar Firebase posteriormente
  // Inicializar Firebase (opcional: requer arquivo de configuração)
  /*
  try {
    await Firebase.initializeApp();
    await PushService.init();
  } catch (e) {
    // Se Firebase não estiver configurado, continuamos sem push
  }
  */
  
  runApp(const PontoDigitalApp());
}

class PontoDigitalApp extends StatelessWidget {
  const PontoDigitalApp({super.key});

  @override
  Widget build(BuildContext context) {
    return ValueListenableBuilder<ThemeMode>(
      valueListenable: ThemeService.themeModeNotifier,
      builder: (context, mode, child) {
        return MaterialApp(
          title: 'Ponto Digital',
          theme: AppTheme.lightTheme,
          darkTheme: AppTheme.darkTheme,
          themeMode: mode,
          home: const LoginScreen(),
          debugShowCheckedModeBanner: false,
        );
      },
    );
  }
}

